### ISSUE TITLE
Medios de transporte disponibles

### ISSUE THREAD

**Issue by cmh1008ubu** [cmh1008ubu/Viaje-a-Europa#1]

**Comment by cmh1008ubu** [comment]
**_Medios de transporte disponibles_**

Se ha de tener en cuenta que los siguientes medios de transporte presentados no se han clasificado en este issue por nivel de precio.

**Comment by msp1030** [comment]
- Vuelos: a destinos alejados
- Tren: entre Países cercanos
- Autobús/ Tranvía: dentro de la ciudad
- Ferries: destinos tales como islas
- Coche: alquiler de coche en caso de ser necesario
