### ISSUE TITLE
Ciudades a visitar

### ISSUE THREAD

**Issue by msp1030** [cmh1008ubu/Viaje-a-Europa#3]
- Milán
- Praga
- Viena
- Berlín
- Sofía
- Oslo

**Comment by shr1006** [comment]
- Milán: Canova Hotel
- Praga: Grandium Hotel
- Viena: Leonardo Hotel
- Berlín: Scandic Berlin Hotel
- Sofía: Sofia Palace Hotel
- Oslo: Smarthotel Oslo
